doctor_atiendea:
    resource: "@DoctorBundle/Resources/config/routing/atiendea.php"
    prefix:   /atiendea

doctor_paciente:
    resource: "@DoctorBundle/Resources/config/routing/paciente.php"
    prefix:   /paciente

doctor_doctor:
    resource: "@DoctorBundle/Resources/config/routing/doctor.php"
    prefix:   /doctor

