<?php

namespace DoctorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtiRepository extends EntityRepository
{
}
